export const FETCH_PACKAGE_LIST = 'FETCH_YOUTUBE_LIST';
export const FETCH_PACKAGE_LIST_SUCCESS = 'FETCH_YOUTUBE_LIST_SUCCESS';
export const SAGA_CLEAR_YOUTUBE_RESULT = 'SAGA_CLEAR_YOUTUBE_RESULT';
export const CLEAR_YOUTUBE_RESULT = 'CLEAR_YOUTUBE_RESULT';
